name: Build and release
on:
  workflow_dispatch:
jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and release
        uses: qcastel/github-actions-maven-release@master
        with:
          release-branch-name: "main"
          git-release-bot-name: "InternalErrorGitCi"
          git-release-bot-email: "internalerrorgitci@gmail.com"
          access-token: ${{ secrets.CI_ACCESS_TOKEN }}