name: Deploy to heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to heroku
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "tasks-server"
          heroku_email: "${{ env.EMAIL }}"