name: Build and Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Maven Settings
        uses: s4u/maven-settings-action@v2
        with:
          servers: '[{"id": "github", "username": "philipp.gatzka@swissperform.ch", "password": "${{ secrets.PACKAGES_TOKEN }}"}]'
          githubServer: false
      - name: Publish to GitHub Packages
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}